# Generated by Django 5.2.8 on 2025-12-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('skills_required', models.TextField(help_text='Comma separated skills')),
                ('experience_required', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('last_date_to_apply', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
