# Generated by Django 5.2.8 on 2025-11-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Job Seeker')], default='jobseeker', max_length=20),
        ),
    ]
